// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: measures.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ch.heigvd.iict.dma.protobuf;

@kotlin.jvm.JvmName("-initializemeasureAck")
public inline fun measureAck(block: ch.heigvd.iict.dma.protobuf.MeasureAckKt.Dsl.() -> kotlin.Unit): ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck =
  ch.heigvd.iict.dma.protobuf.MeasureAckKt.Dsl._create(ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `MeasureAck`
 */
public object MeasureAckKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck = _builder.build()

    /**
     * `uint32 id = 1;`
     */
    public var id: kotlin.Int
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `uint32 id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `.Status status = 2;`
     */
    public var status: ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.Status
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.Status status = 2;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck.copy(block: `ch.heigvd.iict.dma.protobuf`.MeasureAckKt.Dsl.() -> kotlin.Unit): ch.heigvd.iict.dma.protobuf.MeasuresOuterClass.MeasureAck =
  `ch.heigvd.iict.dma.protobuf`.MeasureAckKt.Dsl._create(this.toBuilder()).apply { block() }._build()

